name: DotMH Publish Actions
run-name: '${{ github.actor }} - ${{ github.workflow }} - ${{ github.run_number }}'
on:
  push:
    branches:
      - 'main'

jobs:
    publish-bases:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: extractions/setup-just@v1
              with:
                just-version: 1.5.0
            - name: Build base container
              run: just build
            - name: Publish base container
              run: just action-publish devcontainer ${{ github.actor }} ${{secrets.GITHUB_TOKEN}}
            - name: Build base cloud container
              run: just build devcontainer-cloud Cloud.Dockerfile
            - name: Publish base cloud container
              run: just action-publish devcontainer-cloud ${{ github.actor }} ${{secrets.GITHUB_TOKEN}}

    publishes-dev-containers:
      runs-on: ubuntu-latest
      needs: publish-bases
      permissions:
        contents: read
        packages: write
        id-token: write
      strategy:
        matrix:
          container:
            - file: Go.Dockerfile
              container: go
            - file: Node.Dockfile
              container: node
          base:
            - devcontainer
            - devcontainer-cloud
      steps:
        - uses: actions/checkout@v4
        - uses: extractions/setup-just@v1
          with:
            just-version: 1.5.0
        - name: Build base container
          run: just build ${{matrix.base}}-${{matrix.container.container}} ${{matrix.container.file}} ${{matrix.base}}
        - name: Publish base container
          run: just action-publish ${{matrix.base}}-${{matrix.container.container}} ${{ github.actor }} ${{secrets.GITHUB_TOKEN}}